AWSTemplateFormatVersion: "2010-09-09"

Description: "Builds stack with no resources"

Conditions:
  CondCreate: !Equals
    - !Ref AWS::Region
    - !Ref AWS::AccountId
Resources:
  SSMParameter:
    Type: AWS::SSM::Parameter
    Condition: CondCreate
    Properties:
      Name: "NotCreated"
      Type: String
      Value: "NotCreated"
