AWSTemplateFormatVersion: "2010-09-09"
Description: "Pipeline configuration to deploy CloudFormation templates from
              Github to single account."
Parameters:
  ParamGithubAccount:
    Type: String
    Description: GitHub account hosting the source repository for the pipeline.
  ParamGithubRepo:
    Type: String
    Description: GitHub repository that serves as the source for the pipeline.
  ParamGithubBranch:
    Type: String
    Default: main
    Description: GitHub branch to serve as the source for the pipeline
  ParamStackName:
    Type: String
    Description: Name of Stack to be updated.
  ParamTemplateFile:
    Type: String
    Description: "Name of CloudFormation template file in the repository
                 to use for updating stack."
  ParamTemplateConfigFile:
    Type: String
    Description: "(Optional) Name of the CloudFormation parameters file
                  in the repositor to use for updating stack."
  ParamApprovalStage:
    Type: String
    AllowedValues:
      - true
      - false
    Description: Inserts an approval stage before executing the change set.
    Default: true
  ParamDetectChanges:
    Type: String
    AllowedValues:
      - true
      - false
    Description: "Determines whether the pipeline will automatically
                  be started on a commit to the git branch and repo specified.
                  If set to 'true', the pipeline starts automatically when
                  the commit is made.
                  If set to 'false', the pipeline only runs if it is
                  started manually."
    Default: false

Conditions:
  CondApprovalStage: !Equals
    - !Ref ParamApprovalStage
    - true
  CondTemplateConfigFile: !Not
    - !Equals
      - !Ref ParamTemplateConfigFile
      - ''
  CondDetectChanges:
    !Equals
      - !Ref ParamDetectChanges
      - true


Resources:
  IAMRoleCodeBuildProject:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        -
          PolicyName: ArtifactBucketObjects
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource:
                  - Fn::Join: ['',['arn:aws:s3:::',!Ref S3BucketArtifactStore,'/*']]
        -
          PolicyName: CWLogStream
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
        -
          PolicyName: CWLogGroup
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
        -
          PolicyName: ArtifactBucket
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action:
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                Resource:
                  - Fn::Join: ['',['arn:aws:s3:::',!Ref S3BucketArtifactStore]]

      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action: sts:AssumeRole
  IAMRoleCodePipelinePipeline:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        -
          PolicyName: IAMPass
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt IAMRoleCloudformation.Arn
            Version: 2012-10-17
        -
          PolicyName: Codestar
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action: codestar-connections:UseConnection
                Resource: !Ref CodeStarConnectionsConnectionGitHub
            Version: 2012-10-17
        -
          PolicyName: CodeBuild
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuildBatches
                  - codebuild:StartBuildBatch
                Resource: !GetAtt CodeBuildProject.Arn
            Version: 2012-10-17
        -
          PolicyName: Cloudformation
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                Resource:
                  - !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${AWS::StackName}/*
                  - !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${ParamStackName}/*
            Version: 2012-10-17
        -
          PolicyName: S3BucketAccess
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetBucketPolicy
                  - s3:GetBucketLocation
                Resource:
                  - Fn::Join: ['',['arn:aws:s3:::',!Ref S3BucketArtifactStore]]
            Version: 2012-10-17
        -
          PolicyName: S3ObjectAccess
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:PutObjectACL
                  - s3:GetObjectACL
                Resource:
                  - Fn::Join: ['',['arn:aws:s3:::',!Ref S3BucketArtifactStore, '/*']]
            Version: 2012-10-17
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
  IAMRoleCloudformation:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        -
          PolicyName: CloudformationStackDeployments
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action:
                  - cloudformation:*
                  - ec2:*
                  - iam:CreateRole
                  - iam:CreatePolicy
                  - iam:GetRole
                  - iam:DeleteRole
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - s3:*
                  - lambda:*
                  - sqs:*
                  - dynamodb:*
                  - iam:*
                  - logs:*
                  - cloudwatch:*
                  - events:*
                  - codestar-connections:PassConnection
                  - ssm:*
                  - apigateway:*
                Resource: "*"
            Version: 2012-10-17
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
  S3BucketArtifactStore:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
          ServerSideEncryptionConfiguration:
              -   ServerSideEncryptionByDefault:
                      SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: "Enabled"
      LifecycleConfiguration:
        Rules:
          -
            Status: "Enabled"
            ExpirationInDays: 30
            Id: Remove after 30 days
            NoncurrentVersionExpirationInDays: 30
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      ConcurrentBuildLimit: 1
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          -
            Name: S3_BUCKET_ARTIFACT_STORE
            Value: !Ref S3BucketArtifactStore
          -
            Name: CORE_TEMPLATE
            Value: !Ref ParamTemplateFile
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      QueuedTimeoutInMinutes: 5
      ResourceAccessRole: !GetAtt IAMRoleCodeBuildProject.Arn
      ServiceRole: !GetAtt IAMRoleCodeBuildProject.Arn
      Source:
        BuildSpec:  |
          version: 0.2
          phases:
            install:
              commands:
                - printenv
                - ls -R
            build:
              commands:
                - aws cloudformation package --template-file $CORE_TEMPLATE --s3-bucket $S3_BUCKET_ARTIFACT_STORE --output-template-file transformed-$CORE_TEMPLATE
                - ls -R
          artifacts:
            files:
              - '**/*'
            discard-paths: no
        Type: CODEPIPELINE
      TimeoutInMinutes: 5
  CodeStarConnectionsConnectionGitHub:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: !Ref AWS::StackName
      ProviderType: GitHub
  CodePipelinePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
        ArtifactStore:
          Location: !Ref S3BucketArtifactStore
          Type: S3
        RestartExecutionOnUpdate: false
        RoleArn: !GetAtt IAMRoleCodePipelinePipeline.Arn
        Stages:
          -
            Name: SourceStage
            Actions:
              -
                ActionTypeId:
                  Category: Source
                  Owner: AWS
                  Provider: CodeStarSourceConnection
                  Version: 1
                Configuration:
                  ConnectionArn: !Ref CodeStarConnectionsConnectionGitHub
                  FullRepositoryId: !Sub "${ParamGithubAccount}/${ParamGithubRepo}"
                  BranchName: !Ref ParamGithubBranch
                  DetectChanges:
                    !If
                      - CondDetectChanges
                      - true
                      - false
                Name: SourceAction
                OutputArtifacts:
                  - Name: SourceActionOutput
                RunOrder: 1
          -
            Name: BuildStage
            Actions:
              -
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: 1
                Configuration:
                    ProjectName: !Ref CodeBuildProject
                InputArtifacts:
                  - Name: SourceActionOutput
                Name: BuildAction
                OutputArtifacts:
                  - Name: BuildActionOutput
                #RoleArn: !GetAtt IAMRoleCodePipelinePipeline.Arn
                RunOrder: 1
          -
            Name: CreateChangeSetsDeployStage
            Actions:
              -
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: 1
                Configuration:
                  ActionMode: CHANGE_SET_REPLACE
                  StackName: !Ref ParamStackName
                  Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                  ChangeSetName: !Sub ${ParamStackName}-ChangeSet
                  RoleArn: !GetAtt IAMRoleCloudformation.Arn
                  TemplatePath: !Sub "BuildActionOutput::transformed-${ParamTemplateFile}"
                  TemplateConfiguration: !Sub "BuildActionOutput::${ParamTemplateConfigFile}"
                InputArtifacts:
                  - Name: BuildActionOutput
                Name: CoreTemplateCreateChangeSetAction
                OutputArtifacts:
                  - Name: CoreTemplateCreateChangeSetActionOutput
                RunOrder: 1
          -
            !If
              - CondApprovalStage
              - Name: ChangeSetsApprovalStage
                Actions:
                  -
                    ActionTypeId:
                      Category: Approval
                      Owner: AWS
                      Provider: Manual
                      Version: 1
                    Configuration:
                      CustomData: Please approve the change sets.
                    RunOrder: 1
                    Name: ChangeSetsApprovalStageAction
              - !Ref "AWS::NoValue"
          -
            Name: ExecuteChangeSetsDeployStage
            Actions:
              -
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: 1
                Configuration:
                  ActionMode: CHANGE_SET_EXECUTE
                  StackName: !Ref ParamStackName
                  Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                  ChangeSetName: !Sub ${ParamStackName}-ChangeSet
                InputArtifacts:
                  - Name: CoreTemplateCreateChangeSetActionOutput
                Name: CoreTemplateExecuteChangeSetAction
                RunOrder: 1
